Repository wrappid/app-builder-module, pull requests merged in 2024-02, with the labels that each got.

#21 fix: :fire: correct the typo
  app/styles/DefaultModuleStyles.js
  app/styles/LargeModuleStyles.js
  app/styles/MediumModuleStyles.js
  app/styles/SmallModuleStyles.js
  app/styles/XLargeModuleStyles.js
  app/styles/XXLargeModuleStyles.js
Labels: bug

#23 refactor: revamp to typescript
  .github/scripts/attribution_header_adder.sh
  .github/workflows/auto-create-and-merge-pr.yml
  package-lock.json
  package.json
  service/constants/whereConstants.ts
  service/controllers.registry.ts
  service/controllers/appbuilder.controller.js
  service/controllers/appbuilder.controller.ts
  service/controllers/business.controller.ts
  service/controllers/database.controller.ts
  service/controllers/forms.controller.js
  service/controllers/forms.controller.ts
  service/functions.registry.js
  service/functions.registry.ts
  service/functions/appbuilder.functions.ts
  service/functions/businessEntity.get.helper.ts
  service/functions/businessEntity.helper.ts
  service/functions/businessEntity.post.helper.ts
  service/functions/formSchema.helper.ts
  service/middlewares.registry.js
  service/middlewares.registry.ts
  service/models.registry.js
  service/models.registry.ts
  service/models/BusinessEntitySchemas.model.ts
  service/models/FormSchemas.model.ts
  service/models/Pages.model.ts
  service/models/TestDatas.model.js
  service/routes.registry.ts
  service/routes/appbuilder.routes.js
  service/tasks.registry.js
  service/tasks.registry.ts
  service/utils/strings.utils.ts
  service/validations.registry.js
  service/validations.registry.ts
Labels: enhancement

#26 fix: fix getNoAuthFormSchema
  service/controllers/forms.controller.ts
Labels: enhancement

#27 merge: from development to main with form schema related issue fix
  service/controllers/forms.controller.ts
Labels: bug, enhancement

#30 merge: Development into main
  .eslint/service/.eslintrc.js
  .eslintrc.js
  package-lock.json
  package.json
  service/constants/whereConstants.ts
  service/controllers.registry.ts
  service/controllers/appbuilder.controller.ts
  service/controllers/business.controller.ts
  service/controllers/database.controller.ts
  service/controllers/forms.controller.ts
  service/controllers/test.controller.ts
  service/functions.registry.ts
  service/functions/appbuilder.functions.ts
  service/functions/businessEntity.get.helper.ts
  service/functions/businessEntity.helper.ts
  service/functions/businessEntity.post.helper.ts
  service/functions/formSchema.helper.ts
  service/functions/test.functions.ts
  service/middlewares.registry.ts
  service/middlewares/test.middleware.ts
  service/models.registry.ts
  service/models/BusinessEntitySchemas.model.ts
  service/models/FormSchemas.model.ts
  service/models/Pages.model.ts
  service/models/TestDatas.model.ts
  service/models/Users.model.ts
  service/routes.registry.ts
  service/tasks.registry.ts
  service/tasks/TestTask.ts
  service/utils/strings.utils.ts
  service/validations.registry.ts
  service/validations/test.validation.ts
Labels: enhancement
